name: PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: raabf/latex-versions:texlive2022
    steps:
      - uses: actions/checkout@v2
      - name: Build Example PDF
        run: |
          ls
          make all