name: Build-&-Deploy-PDF

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: raabf/latex-versions:texlive2020
    steps:
      - uses: actions/checkout@v2
      - name: Build Example PDF
        run: |
          ls
          make all
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: public
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}